server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/be_greenhouse"
    username: kienle
    password: kienle@2105
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey : "DADN_CNPM_L08_Nhom2_HK242_1234567890"

mqtt:
  brokerUrl: "tcp://io.adafruit.com:1883"
  username: "htann04"
  apiKey: "${MQTT_API_KEY}"
  clientId: "be_greenhouse"
